### ISSUE TITLE
Just work once (installe using Alcatraz)

### ISSUE THREAD

**Issue by nartex** [viniciusmo/extract-localizable-string-plugin-xcode#11]
Hi there,
I gave a shot to your plugin, installing it with Alcatraz, and it worked in the first place.
But after restarting XCode, the shorcut doesn't appear in the refactor menu.
I tried reinstalling it using Alcatraz (Remove then Install), and the shortcut appear but doesn't do anything.
I don't face any other problems with other plugins installed using Alcatraz.

**Comment by viniciusmo** [comment]
Hi nartex,

Xcode Version?

Thanks

**Comment by nartex** [comment]
Latest, Version 6.3 (6D570)
Thnaks for your support :)

**Comment by segunlee** [comment]
I have same problem, my Xcode version is 6.3
Thanks

**Comment by consuelita** [comment]
Same issue with Xcode version 6.3.1
