### ISSUE TITLE
Not working with Swift on Xcode 6.3.2

### ISSUE THREAD

**Issue by va3093** [viniciusmo/extract-localizable-string-plugin-xcode#13]
Hey,

I am really keen to use this but can't seem to get it to work on xcode 6.3.2 working with swift. 

The menu item isn't showing on the menu bar.

![screen shot 2015-05-29 at 9 49 01 am](https://cloud.githubusercontent.com/assets/8058892/7879415/196a6b96-05e8-11e5-893c-260043d78449.png)

And when I type the keyboard shortcut nothing happens either. 

Please let me know if you would like some more information. 

Thanks for what looks like a great tool.

Villy

**Comment by nadirloutfi** [comment]
Hi,
Same problem here.
Any progress on this issue.
Great tool
Thanks,
Nadir

**Comment by evercry** [comment]
Hey, 
Same problem here too.

**Comment by chintan1891** [comment]
@evercry  @nadirloutfi @va3093  Please checkout my forked source code.

https://github.com/viniciusmo/extract-localizable-string-plugin-xcode/pull/15

**Comment by viniciusmo** [comment]
Thxs man
