### ISSUE TITLE
xCode 6.4 support

### ISSUE THREAD

**Issue by Lutzifer** [viniciusmo/extract-localizable-string-plugin-xcode#16]
Does not work for me at the moment in xCode 6.4, no menu entry is visible

**Comment by chintan1891** [comment]
Download Source code.
Use following command to get GUID of Xcode. 
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID 
On executing above command you will get output somthing like, “E969541F-E6F9-4D25-8158-72DC3545A6C6”

Now add this GUID into Info.plist under "DVTPlugInCompatibilityUUIDs" key. Quit Xcode & restart it.
Plugin will work now.

**Comment by chintan1891** [comment]
@Lutzifer  This branch has Xcode 6.4 support : https://github.com/chintan1891/extract-localizable-string-plugin-xcode

**Comment by Lutzifer** [comment]
thank you

**Comment by va3093** [comment]
Thanks!
