### ISSUE TITLE
New features into Plugin

### ISSUE THREAD

**Issue by chintan1891** [viniciusmo/extract-localizable-string-plugin-xcode#17]
Hi @viniciusmo ,
https://github.com/chintan1891/extract-localizable-string-plugin-xcode
I have forked source code of this plugin and tried to enhance its features to make it more usable.
My forked source code contains below features:
- Removed "Choose Localizable File" menu. Plugin will now find all Localizable.strings files and add key-value pair into it.
- Plugin will validate if user is not adding a duplicate key.
- Plugin will alert user if he/she tries to add any value which is already exists.
- Plugin now provides option to add comment for any Localizable string.
- Current plugin stores Localizable file path into NSUserDefaults, due to which if i switch my project, this plugin will add key value pair to Localizable.strings file of old project. Fixed this bug.
- Added Cancel button in "Extract Lcoalizable String" popup.

Please look into my forked source code, and provide your suggestion. I can create a pull request if you want to add these features.

**Comment by viniciusmo** [comment]
@chintan1891 

Nice work! You can perform the pull request that I accept . Congratulations for the great job.

thanks

**Comment by chintan1891** [comment]
Thanks @viniciusmo .
I have created a pull request. https://github.com/viniciusmo/extract-localizable-string-plugin-xcode/pull/18

**Comment by va3093** [comment]
Thanks guys!
