### ISSUE TITLE
The default localizable file not found.Please create your default localizable file.

### ISSUE THREAD

**Issue by croccio** [viniciusmo/extract-localizable-string-plugin-xcode#7]
xcode 6.1

rename info.plist as Filo-Info.plist, added Localizable.strings file but i get that error.

please add the possibility to select manually the file... so you have nobody with this error

**Comment by crazyramirez** [comment]
Same issue for me

**Comment by viniciusmo** [comment]
Hi,
I released a new version 2.0.1 with support for choosing the file. You can test please?

**Comment by croccio** [comment]
in this days i’ll try it, thank you

**Comment by croccio** [comment]
it works :D:D thank you :D:D
 but every time i extract string it ask me to select file so for 5 strings i gave to selected 5 time file. I think the best is to use every time the first file selected with a voice in menu that allow me to change it.

**Comment by viniciusmo** [comment]
Thanks @croccio 
I will make this :)

**Comment by croccio** [comment]
Thank you very much :) this plugin is great :D

**Comment by viniciusmo** [comment]
I released a new version 2.0.2 :)

**Comment by croccio** [comment]
it works :D tank you very muuuuuuch :D

**Comment by HeltonSampaio** [comment]
Hello, even with the 2.0.2 update, I still can not set my default file. Please help me.
