### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by tranngoclinh88** [viniciusmo/extract-localizable-string-plugin-xcode#9]
After select and choose "Extract Localization String", nothing appears.

**Comment by viniciusmo** [comment]
Hi @tranngoclinh88 ,

What is your version of Xcode? 
You followed the steps of the video? 
Could you send me the piece of code you tried to extract the string?

Thanks :)

**Comment by arnaudWasappli** [comment]
Me neither. When I select the text he doesn't find the Localisable.strings so I clic on "Choose localisable file" and after I clic open the same window appear.

![capture d ecran 2015-03-20 a 15 26 16](https://cloud.githubusercontent.com/assets/7737273/6753345/8c41f26a-cf15-11e4-8486-25ef12cb85de.png)

**Comment by viniciusmo** [comment]
Thanks for the input :). I will verify this .

**Comment by ender3** [comment]
I can also verify that I see identical results to @arnaudWasappli

**Comment by tranngoclinh88** [comment]
@viniciusmo My Xcode version is 6.2
